### PR TITLE
Rename ChartBackend -> CBProgram

### PR DESCRIPTION
**Pull request by timbod7**
This ended up touching many more files than I expected. Nevertheless, I think it is a fair bit clearer.

@sid-kap: what do you think?

### CODE REVIEW

**Comment by sid-kap** [comment]
What does "CB" stand for?

**Comment by timbod7** [comment]
Chart Backend

I thought that ChartBackendPrograms was too long as a name.

**Comment by sid-kap** [comment]
Hmm... I personally think that it would be clearer if we avoid abbreviations. 

Earlier you suggested using "Instructions" in the name--- I think this is clearer than "Program". What do you think about "ChartInstructions" or "BackendInstructions"?

**Comment by timbod7** [comment]
The term `Program` is consistent with the underlying operational monad:

https://hackage.haskell.org/package/operational-0.2.3.2/docs/Control-Monad-Operational.html

It kind of makes sense to me - a Program is a sequence of Instrutions.

How about BackendProgram ?

**Comment by sid-kap** [comment]
Sure, that sounds good to me.

**Pull request merged**
