### PR TITLE
Make font loading much faster for diagrams backend

### PR DESCRIPTION
**Pull request by sid-kap**
On my computer, this brings the runtime of a simple diagrams-backend chart from >1s to 0.2s. (This is pretty close to the optimal time, which is 0.1s if no fonts are loaded at all.)

Changes:
- Added Serialize instance for PreparedFont. (I used cereal instead of binary because is much faster for floating-point numbers. See https://www.reddit.com/r/haskell/comments/44w15q/psa_if_youre_serializing_floating_point_numbers/ With binary, I could only get 0.3-0.35s for this program.)
- Added a script (MakeFontBinaries.hs) to convert svg files to cereal binary files. (It would be nice if we could get the compiler to run this script before compiling the other files.)
- Embed serialized fonts into binary for fast loading
- Make `loadSansSerifFiles` load the fonts from the embedded serialized fonts instead of from the SVG files

TODO/questions:
- [x] Get diagrams/SVGFonts/pull/19 PR merged (This depends on that PR)
- [ ] Update `loadCommonFonts` to use serialized fonts
- [ ] Should we try to upstream some of these instances (especially the Generic ones) to diagrams-lib and SVGFonts?
- [ ] Should we make `Get` and `Put` objects instead of instances, so that the orphan instances don't cause OverlappingInstances problems?
- [ ] Somehow make cabal run the MakeFontBinaries script before compiling Diagrams.hs

### CODE REVIEW

**Comment by timbod7** [comment]
Nice. Can you measure the peformance through the harness? The harness produces 62 charts (and demo outputs). On my mac, comparing cairo vs diagrams:

```
$ time ../.stack-work/install/x86_64-osx/lts-5.5/7.10.3/bin/chart-harness charts-cairo --svg
...
real	0m0.750s
user	0m0.526s
sys	0m0.066s

$ time ../.stack-work/install/x86_64-osx/lts-5.5/7.10.3/bin/chart-harness charts-diagrams --svg
...
real	0m32.251s
user	0m31.169s
sys	0m0.677s
$
```

**Comment by sid-kap** [comment]
Are the times you posted above with or without the patch?

**Comment by timbod7** [comment]
They are for the unmodified 1.6 code from hackage.

**Comment by sid-kap** [comment]
Here are my times:
```
# master branch
# time .stack-work/install/x86_64-linux/nightly-2016-03-15/7.10.3/bin/chart-harness charts-cairo --svg
.stack-work/install/x86_64-linux/nightly-2016-03-15/7.10.3/bin/chart-harness   0.55s user 0.02s system 99% cpu 0.581 total
# time .stack-work/install/x86_64-linux/nightly-2016-03-15/7.10.3/bin/chart-harness charts-diagrams --svg
.stack-work/install/x86_64-linux/nightly-2016-03-15/7.10.3/bin/chart-harness   34.10s user 0.37s system 98% cpu 34.929 total

# my branch
# time .stack-work/install/x86_64-linux/nightly-2016-03-15/7.10.3/bin/chart-harness charts-diagrams --svg
.stack-work/install/x86_64-linux/nightly-2016-03-15/7.10.3/bin/chart-harness   30.61s user 0.25s system 99% cpu 30.886 total
```

I think the improvement is only in the initial font-loading step, which only runs once in the test program.

**Comment by timbod7** [comment]
That's a shame - it seems that rendering with diagrams is still ~60x slower than rendering with cairo, even when the font loading time is eliminated....

**Comment by timbod7** [comment]
It's a little hard to see what functional code changes you have made, versus just refactors. Are any changes to the `Graphics/Rendering/Chart/Backend/Diagrams.hs` essential, or could the new font loading code go in a separate file, which just exported a variant of the `loadSansSerifFonts` function?

Other thoughts:

> Should we try to upstream some of these instances (especially the Generic ones) to diagrams-lib and SVGFonts?

Definitely - I want to avoid orphan instances in the library.
 
> Somehow make cabal run the MakeFontBinaries script before compiling Diagrams.hs

This is essential too. For chart to work in stackage the build process must be automated through cabal.

**Comment by bergey** [comment]
Please send a PR with the instances.

I have a student who will be looking at Diagrams performance for a couple of months this spring.  We can include some Charts examples in the profiling runs.  Reducing the time in font loading will make tracking down other issues that much easier.

**Comment by sid-kap** [comment]
@timbod7 Sorry for mixing refactors with other changes in the same pull request. The only function that was changed is `loadSansSerifFonts`. (If you guys in favor of this change, I would like to make similar changes to `loadCommonFonts` as well.)

So the new font loading could go in a separate file. Do you want me to put it in a separate file? If so, would you want to keep the old `defaultEnv`, or make `defaultEnv` depend on the new `loadSansSerifFonts`?

One more thing: since `loadSansSerifFonts` now returns a `FontSelector Double` instead of `FontSelector n`, I had to change the return type of `defaultEnv` from `DEnv n` to `DEnv Double`. Is this an issue? I wouldn't mind generalizing the type again, but I hope this doesn't hurt performance.

**Comment by sid-kap** [comment]
@bergey Which instances would you be comfortable adding to Diagrams? `Generic`, `Serialize`, or both? I assume that you would be hesitant to add a `cereal` dependency for `diagrams-lib`.
 
If we don't want to add `Serialize` instances to diagrams-lib and we don't want to create orphan instances, we could manually create `Put` and `Get` objects in this code instead of making `Serialize` instances. (This might require writing more code though, since I don't think we can auto-derive these.)

Another option could be to create a `diagrams-cereal` package which only contains the `Serialize` instances.

**Comment by sid-kap** [comment]
@timbod7 Regarding the build automation, we have a few options:

1) Store the `*.cereal.bin` files in git, so that we don't need to rebuild them every time. [Drawback: it's generally bad practice to keep generated files in git.]
2) Move the serialization logic into compilation unit. This is necessary because the `MakeFontBinaries` script must be run before compiling `chart-diagrams`, and the serialization logic must be compiled before running `MakeFontBinaries`. Do you know of a good way to do this? The only way I can think of is to make another package `Chart-diagrams-serialize` such that `MakeFontBinaries` depends on `Chart-diagrams-serialize`, `Chart-diagrams` depends on `Chart-diagrams-serialize`, and we tell cabal to run `MakeFontBinaries` before building `Chart-diagrams`. It would be nice to do this without creating an extra library.

**Comment by bergey** [comment]
`diagrams-lib` already depends on `cereal` indirectly by way of `linear`.  So I'd be happy to take both sets of instances.  Please put them in whatever module the type is defined in, to avoid orphans.

**Comment by sid-kap** [comment]
Thanks for the quick response! I'll send you the PR soon.

**Comment by timbod7** [comment]
I can see the value in this code, but it's not specific to charts - any code that uses svg based fonts may need this speedup. Should the core changes be made instead to the SVGFonts library? I can image that it would end up with something like:

```
loadFont :: (Read n, RealFloat n) => FilePath -> IO (PreparedFont n)  # Existing from .svg file
loadCerealFont:: FilePath -> IO (PreparedFont Double)  # Precanned binary format
decodeCerealFont:: ByteString -> Maybe (PreparedFont Double) # In memory font data
```

That way the fast loading would be available to any diagrams code?

**Comment by sid-kap** [comment]
That's a good point.

If the two pull requests I just sent (diagrams/diagrams-lib#271 and diagrams/SVGFonts#20) get merged, then we will be able to get rid of `chart-diagrams/Graphics/Rendering/Chart/Backend/Serialize.hs`.

In that case, all that will be left in `charts-diagrams` will be the small amount of font loading/decoding logic in `Diagrams.hs`. So what you suggested is basically what will happen if the two PRs get merged.

**Comment by sid-kap** [comment]
The two other PRs got merged, so there is now much less code in this PR. Are you interested in incorporating these changes? If so, I can update `loadCommonFonts` to also use serialized fonts, and I can also figure out how to make cabal prepare the fonts before a build.

**Comment by timbod7** [comment]
Sorry for not getting back to this for so long. The change is much simpler and easier to understand now.

Does embedding the fonts in the code account for much of the speed? I suspect that it is it mostly about switching from XML parsing to cereal. Assuming the latter, it may be simpler and tidier to include the `.bin` font files with the release, and load them in lieu of the existing svg ones?

**Comment by sid-kap** [comment]
Sure, that is worth testing. I'll try it and let you know the results!

**Pull request closed without merging**
