### PR TITLE
diagrams-postscript 1.5.0 compatibility

### PR DESCRIPTION
**Pull request by angerman**

### CODE REVIEW

**Comment by timbod7** [comment]
I can't seem to see `diagrams-postscript-1.5.0` on hackage, or as a tag in the github repo. Has it  been published yet?

**Comment by vmchale** [comment]
It is on hackage as of today :)

**Comment by bravit** [comment]
Thanks, @vmchale! I'll look into it shortly.

**Comment by harendra-kumar** [comment]
@timbod7 @bravit can we have this fixed/merged please?

**Pull request merged**
