### PR TITLE
Added LegendPosition.

### PR DESCRIPTION
**Pull request by rdnetto**
This PR adds a field for configuring the position of the legend.

### CODE REVIEW

**Comment by timbod7** [comment]
Sorry for the slow response. The change looks good.

Can you please:
    -  remove the patch for the library version. I update the version with each hackage release, not each commit.
    -  add a test to generate a sample plot with the legend in each location?

**Comment by rdnetto** [comment]
> - remove the patch for the library version. I update the version with each hackage release, not each commit.
> - add a test to generate a sample plot with the legend in each location?

Sure, no problem. I've added the test cases to test 15, since it was already testing related functionality.

**Comment by rdnetto** [comment]
Bump :)

**Comment by timbod7** [comment]
Sorry for being slow. Thanks heaps for the contribution!

**Pull request merged**
