### PR TITLE
Increase lens version bounds

### PR DESCRIPTION
**Pull request by sid-kap**
Follow-up to https://github.com/fpco/stackage/issues/1972

### CODE REVIEW

**Comment by sid-kap** [comment]
Bump?

**Comment by timbod7** [comment]
Sorry I haven't looked at this until now. 

Shouldn't the new constraint be `lens >= 3.9 && < 4.16` ?

**Comment by sid-kap** [comment]
That's right, I'll fix it

**Comment by timbod7** [comment]
Thanks!

**Pull request merged**
