### PR TITLE
Support diagrams-1.3

### PR DESCRIPTION
**Pull request by acowley**
This should be good to go once an [issue](https://github.com/diagrams/diagrams-svg/issues/78) in `diagrams-svg` is resolved. At that point we can nail down the dependencies.

In the meantime, some review of this patch would be good. It's not the prettiest thing in the world.

### CODE REVIEW

**Comment by timbod7** [comment]
Thanks for this! I was worried that it would take me some time to get around to making this change, due to needing to understand the new diagrams API.

I'll take a close look in the next day or so.

**Comment by acowley** [comment]
Any progress on this?

**Comment by cocreature** [comment]
I am also waiting for this. It would be great if you could take a look at it.

**Comment by timbod7** [comment]
Sorry for the delay - I'll be on to it this week.

**Comment by timbod7** [comment]
I just refactored the test harnesses in order to make testing this easier, and then I realised that actually two distinct patches to support diagrams 1.3: this one, and https://github.com/timbod7/haskell-chart/pull/83.

They seem broadly similar - is there a reason to favour one over the other?

**Comment by bgamari** [comment]
@timbod7 I think the real difference is that I try to work with the generalized interfaces provided by diagrams and remain polymorphic in the scalar type in as much code as possible. I also do a variety of whitespace fixes (in separate commits, of course).

**Comment by acowley** [comment]
That's right. I didn't try to maintain the scalar polymorphism as I didn't see that it would be surfaced through Chart. I don't know that there is any downside to the polymorphism (eg inference), so I'd probably go with @bgamari's patch if everything's working.

**Comment by bgamari** [comment]
As it turns out `diagrams-svg-1.3.1` breaks the `SVGOptions` interface; I've pushed a patch to my branch updating usage of it.

**Comment by acowley** [comment]
I thought I'd fixed that in conjunction with upstream. Is this new breakage?

**Comment by bgamari** [comment]
It actually looks like your patch covers it. Not sure how I ended up with the `1.3.0` interface initially.

**Comment by acowley** [comment]
I've rebased to master and bumped `lens` versions as I've got a stream of people struggling due to this. I haven't had time to try @bgamari's variation of this PR, but if this keeps dragging out we'll probably end up with a third PR :smile:

**Comment by timbod7** [comment]
After some tinkering and investigation,I've merged @bgamari's PR to master. Let me know if it works ok for you.

**Comment by acowley** [comment]
Master is now working for me. Thanks!

**Pull request closed without merging**
