### PR TITLE
Bar charts enhancements

### LINKED ISSUE #214: Labels for log scale axis are not readable at all
It's not the worst example but it's bad enough: 
badlog

Counting nines is not pleasant and if we go above/below 10^±15 labels could easily eat half of the plot. And whole 1+9999 thing looks very strange

### PR DESCRIPTION
**Pull request by clayrat**
Supersedes #161, fixes #214 and #223.

This PR contains:

* A fix for incorrect logscale axis label rendering
* Customized labels on individual bars (based on #161)
* Ability to use a logscale axis with bar charts
* Ability to render horizontal bar charts
* Ability to have internal ticks on an indexed axis (e.g., to render grids)
* Various linter fixes 
* A test demonstraring horizontal logscale bar with custom labels and an index grid

### CODE REVIEW

**Comment by clayrat** [comment]
Here's the output of the new test demonstrating added functionality: 
test20

**Comment by clayrat** [comment]
@timbod7 @bravit what do you think?

**Comment by timbod7** [comment]
Oh - dear. I just took a look at #161, and see that it ended in me saying I'd take a look in a few days. in 2017!

**Comment by timbod7** [comment]
A great set of changes. Thank you!

**Pull request merged**
