### PR TITLE
Add data point labels

### PR DESCRIPTION
**Pull request by rdnetto**
This PR adds the ability to annotate scatter plots and bar graphs with labels. The supported options mirror the arguments of `drawTextR`, with some additional support for controlling position relative to the point/bar.

### CODE REVIEW

**Comment by timbod7** [comment]
Thanks for this PR.

Were you aware of the `Graphics.Rendering.Chart.Plot.Annotation` type? I would have expected that it would meet your needs for adding textual annotations to point and line plots.

The bar plots change looks valuable. However I would expect that the anchor values would be the same for each label, and hence could be passed once, rather than on each label. Also, Requiring the two parallel structures:

```
   _plot_bars_values          :: [ (x,[y]) ],
   _plot_bars_labels          :: [[BarLabel]]
```

feels  awkward to me. I think it would be cleaner to just include the labels directly, ie

```
   _plot_bars_values          :: [ (x,[y,String]) ],
```

**Comment by rdnetto** [comment]
I was completely unaware of the Annotations module - I've updated one of the tests/examples to demonstrate it.

I've modified the bar labels code as suggested, and defined a lens to preserve compatibility. It's not quite law abiding, since it always sets the labels to empty strings, but I couldn't think of a better way of handling it.

**Comment by timbod7** [comment]
Thanks - I've taken a quick look, and it looks good now.

I'll review in detail in the next couple of days.

**Comment by timbod7** [comment]
Fixed by #253

**Pull request merged**
