### PR TITLE
Bump to diagrams-svg 1.4

### PR DESCRIPTION
**Pull request by sid-kap**

### CODE REVIEW

**Comment by timbod7** [comment]
Thanks for this - I'm still keen to discuss further API improvements, but it's good to get up to date diagrams compatibilty sorted first.

**Comment by sid-kap** [comment]
Did you get a chance to cut a new release with these changes? I'm not sure how quickly the stackage folks expect us to update the package.

**Comment by timbod7** [comment]
Will do so today.

**Comment by timbod7** [comment]
1.7 now pushed to hackage.

**Comment by sid-kap** [comment]
Awesome! I'll leave a note under the stackage issue.

**Pull request merged**
