### PR TITLE
Bump version bounds for diagrams-svg

### PR DESCRIPTION
**Pull request by sid-kap**
Related to https://github.com/fpco/stackage/issues/1227

### CODE REVIEW

**Comment by sid-kap** [comment]
I'm getting compile errors, so probably shouldn't merge this yet.

**Comment by sid-kap** [comment]
It looks like they've moved away from svg-lucid and now return svg-builder types. We have several functions that return `Svg.Svg ()` from svg-lucid, so it looks like we have two options:

1) make a breaking change to the API, by changing these return types accordingly
2) somehow convert the svg-builder type to `Svg.Svg ()` so that we can retain the same return types

This is somewhat tangential, but I would even be fine with removing every exposed function except those that return `QDiagram`s, since the user can anyways use functions from the diagrams suite to convert a `QDiagram` into a svg, eps, etc.

**Comment by timbod7** [comment]
> I am somewhat in favor of removing every exposed function except those that return QDiagrams

This seems like the cleanest approach, though I'm a little worried about how much boilerplate would be required to convert to an svg, eps etc. User's would be somewhat resistant to writing the code `for renderableToSVG'` whenever they wanted to generate a chart:

```
renderableToSVG' :: Renderable a -> DEnv Double -> (Svg.Svg (), PickFn a)
renderableToSVG' r env =
  let (w, h) = envOutputSize env
      (d, x) = runBackendR env r
      opts = DSVG.SVGOptions (D2.dims2D w h) Nothing T.empty
      svg = D.renderDia DSVG.SVG opts d
  in (svg, x)
'''

**Comment by bergey** [comment]
A fourth option occurs to me:

4) Return `Text` or (UTF-8) `ByteString` instead of the `Svg` type.

I assume most users immediately convert the `Svg` to one of these, so this seems consistent with the convenience of `renderableToSVG'`.

**Comment by sid-kap** [comment]
This is tangential, but I think the many different types of things to render (`ChartBackend`, `Renderable`, and `EC`) the many ways to specify how to render them (`FileFormat`, `FileOptions`, `DEnv`, width, height), and the 14 different rendering functions is a bit overwhelming for new users. I would be in favor of simplifying the module as much as possible.

**Comment by sid-kap** [comment]
Maybe just three functions: `toSvgFile`, `toSvgEmbeddedFile`, and `toEpsFile`, could be sufficient?

**Comment by timbod7** [comment]
> the many different types of things to render

most of these things do form a pipeline, for the various stages of producing a plot. Possibly `FileFormat` and `FileOptions` could be removed.

>  and the 14 different rendering functions is a bit overwhelming for new users

Agreed. Perhaps the `Graphics.Rendering.Chart.Backend.Diagrams` should contain just the minimal functions for each stage in the pipeline, plus the functions you propose.

**Comment by sid-kap** [comment]
I got carried away and made lots of changes to `Diagrams.hs`, some of which aren't really relevant to the issue at hand. Only the changes to `Diagrams.hs` are worth looking at (the other changes are just to fix compile errors resulting from the changes to `Diagrams.hs`). 

I apologize if this is too much changes---I totally understand if you think some of these are going too far. Anyway, here's a rundown of many ideas I have on how to simplify the Diagrams module:

* Remove the `Renderable a -> x` helper functions. It's not hard for the user to simply call `render` and then use the other functions.
* Similarly, remove the `EC a -> x` helper functions, since the user can easily convert EC to `Renderable` using `toRenderable . execEC`.
* Reduce from 14 rendering functions to 3 rendering functions: `toEPSFile`, `toSVGFile`, and `toEmbeddedFontSVGFile`.
* Remove width and height from `DEnv`. This is unnecessary state being passed around---it's only used by the `adjustOutputDiagram` function, yet it's currently being passed to every function. This also makes using the functions simpler for users--- no more `let (w, h) = envOutputSize env` as in the boilerplate example you mentioned above.
* Change the name of `runBackendR` to `runBackendRenderable`. It is not clear what the `R` means, so might as well be explicit.
* Change the return type of `loadSansSerifFonts` and `loadCommonFonts` to `FontSelector n` instead of `IO (FontSelector n)`. I believe this is an appropriate use of `unsafePerformIO` because we are including the font files in the library, so there should be no reason why the font file would be missing. Also, since we included the files, we know that there won't be parsing errors. (There is, however, the possibilty that `loadFont` might print output when it encounters an error. To prevent this from happening, we might want to switch to a pure function in SVGFonts, like [loadFont'](https://github.com/diagrams/SVGFonts/blob/master/src/Graphics/SVGFonts/ReadFont.hs#L350). )

**Comment by timbod7** [comment]
I think all of these changes are for the better, with the exception of the unsafePerformIO. The library may be installed incorrectly, or the user may be deploying a binary, and need to manually ensure the fonts are in the correct place - diagnosis is harder when the IO exception is thrown lazily from pure code.

The other changes are good though - I'm happy for them to be merged, and for an API breaking release to be made.

(I haven't looked at the changes outside Diagrams.hs - I'm assuming they are just test tweaks to match the API changes).

**Comment by sid-kap** [comment]
Thanks for looking over this! I'll go ahead and undo the `unsafePerformIO` changes.

**Comment by sid-kap** [comment]
Should we change the return type of `toEPSFile`, `toSVGFile`, and `toEmbeddedFontSVGFile`, from `IO a` to `IO ()`? For the "quick-and-dirty save my plot to a file" use case, users probably don't care for the return value.

**Comment by timbod7** [comment]
I don't feel strongly either way. toEPS file needs to be composed with other functions to actually draw something, so having to compose it with `void $` doesn't seem so bad.

To see where all this is headed, what will the example at the bottom of this page:

https://github.com/timbod7/haskell-chart/wiki/How-to-use-backends

look like after your changes?

**Comment by sid-kap** [comment]
The example would look like
```haskell
main1 [format] = do
  env <- defaultEnv vectorAlignmentFns
  let chart' = render (800, 600) chart
  void $ case format of
    "svg" -> toSVGFile chart' 800 600 env "example5.svg" 
    "eps" -> toEPSFile chart' 800 600 env "example5.eps" 
```
If the example was using the easy API that returns a `ChartBackend a` type, then the additional `render (800, 600)` step would not be needed. 

I'm curious: when you're making vector graphics, does it usually make sense to use `vectorAlignmentFns`? If so, we can make `defaultEnv` use this by default.

**Comment by sid-kap** [comment]
The example would be even slicker if we had `defaultEnv vectorAlignmentFns :: DEnv Double` (or `defaultEnv :: DEnv Double`, if we make `vectorAlignmentFns` the default alignment function, as I suggested above), instead of `IO (DEnv Double)`. If we don't want to use `unsafePerformIO`, another option could be to use `file-embed` to embed the file in the binary, so then no `IO` action would be necessary to load the font files.

**Comment by sid-kap** [comment]
Another issue: I'm not sure which data type is most commonly used by users: `EC`, `Renderable`, or `ChartBackend`. Whichever is most convenient for users (I believe it's `EC`, based on the examples in the repo) should be the type that `toXXXFile` takes.

**Comment by timbod7** [comment]
Probably both -`EC` and `Renderable`. The latter is more general, the former can reduce boilerplate for the user (but only if they are using the monadic API to construct charts)..

I've thought about this a little more... where possible we should try and keep the two backends consistent in their API. The cairo backend exports just these two helper functions:

```
renderableToFile :: FileOptions -> FilePath -> Renderable a -> IO (PickFn a)
toFile :: (Default r, ToRenderable r) => FileOptions -> FilePath -> EC r () -> IO ()
```
The first is more general, whereas the second eliminates a little boilerplate, allowing "one line" usage as per the example on this page:

https://github.com/timbod7/haskell-chart/wiki/Monadic-API

Can we aim for the same external API for diagrams backend, such that simple programs would work with just a change in imports?

**Comment by sid-kap** [comment]
Having two functions is a decent option, although in this case that means we have to make 6 functions instead of 3. 

Alternatively, if we have `to{Eps,Svg,EmbeddedFontSvg}File` take a `Renderable a`, then it would be (almost) equally easy to use both:
```
toSvgFile ...args... (toRenderable layout)

-- vs

toSvgFile ...args... $ execEC $ do
  -- monadic stuff
```
I see pros and cons for both. 

One benefit I see of taking a `Renderable`, and not an `EC`, is that it forces the user to understand what's going on in the library/generate a mental model of what each type means. When I first started using Chart, I had no idea what any of `Renderable`, `ChartBackend`, and `EC` even were, and thus was very confused every time I tried to use the library.  (The name `EC` threw me off a lot, since it's not at all obvious what `EC` means! I still don't know what it means.)

**Comment by sid-kap** [comment]
The plots library does something similar to the `EC` monad, except they use plain old `MonadState`. What they do to make their code less verbose is to encourage users to use lens's `&~` operator, which is an alias for `execState`: 
```haskell
myaxis :: Axis B V2 Double
myaxis = r2Axis &~ do
   ribbonPlot (mydata ++ zero_y (reverse mydata)) $ do
     key "ribbon test"
     plotColor  .= red

     strokeEdge .= False
```

I don't feel strongly about this, since I generally don't like operators, but if we really wanted something concise, another option might be to make an operator for `execEC` so that the above example becomes
```haskell
toSvgFile ...args... &~ do
  -- monadic stuff
```
(where `&~` would be replaced with whatever operator we make for `execEC`).

**Comment by timbod7** [comment]
Why not go back to the idea of having just two functions like the cairo backend, that take a defaulted parameter which controls the output  format and size? 

There's definitely pressure from users to be able to write one liners for quick charts  - this is my best effort so far:

```
main = toFile def "test.png" $ plot $ line "lines" [signal [0,(0.5)..400]]
```

**Comment by timbod7** [comment]
I think `Renderable` is reasonably named.
I'd like to rename `ChartBackend` to something else, perhaps `BackendInstructions` or `BackendProgram` - will consider doing this after your changes.
`EC` was (I think) intended to abbreviate `EasyChart` but the fact that I can' remember makes it a bad name. Probably too take to rename it.

**Comment by sid-kap** [comment]
As a side note: To be more concrete, the reason I think there should be one function is the following: 

There is a relationship between `EC` and `Renderable`, namely that `EC` can be converted to `Renderable` using `execEC`. The problem is, having two separate functions, one for each type, can lead to confusion:
* Users will wonder why there are two rendering functions
* Users will wonder why there are two rendering types
* Users won't realize the relationship between the two types.
Having a single rendering function, and encouraging users to realize that `EC`s can be converted to `Renderable`s using `execEC`, removes these causes for confusion.

**Comment by sid-kap** [comment]
By the way, I think `EC` could theoretically be renamed by first, changing its name to `EasyChart` or whatever it should be changed to, and then also exporting a (deprecated) `type EC = EasyChart` alias.

**Comment by sid-kap** [comment]
I've made the functions resemble the original functions you had, although with more descriptive names (`ecToFile` instead of `toFile`, and `chartBackendToFile` instead of `cBackendToFile`). Does this look better? 

I still think there are a few odd things with this approach:

* I don't think FileOptions should have a default instance---users may want to use any of the three backends. Who are we to tell them that SVG is "the default", or that 800x600 is the default?
* I don't really see the benefit of making a type for FileOptions. The user ought to specify the image size and the file type (SVG, EPS, SVGEmbedded) anyway, so we could just make them arguments.

**Comment by sid-kap** [comment]
Can we try to get the minimal required subset of these changes merged? I don't want to hold the diagrams-svg folks back too much

**Comment by timbod7** [comment]
If you can make a pull request that addresses just the upstream issues with diagrams-svg, I'll push it straight away.

As I think I've alluded to above, chart users often aren't behaving as "typical" haskell developers. They aren't interested in seeing a clean pipeline of logical steps in producing a chart (although they want that behind the scenes). Instead, they want the minimum syntax to get a chart. Hence the support for "one line" usage, like:

```
main = toFile def "test.svg" $ plot $ line "lines" [datapoints]
```

If, as you suggest above, you remove `toFile`, and move the size out of the denv and hence have to pass it in to multiple functions, won't the above end up being somewhat more complicated?

**Comment by sid-kap** [comment]
Okay, I'll do as you suggested and make a separate pull request that simply addresses the upstream issues. Thanks!

**Pull request closed without merging**
