### PR TITLE
Raise lens version bounds

### PR DESCRIPTION
**Pull request by sid-kap**
In response to https://github.com/fpco/stackage/issues/1147#issuecomment-216021529

### CODE REVIEW

**Comment by borsboom** [comment]
Can you also raise the bound in the other packages (e.g. https://github.com/timbod7/haskell-chart/blob/master/chart-cairo/Chart-cairo.cabal)

**Comment by timbod7** [comment]
Change pushed, new release (1.7.1) to hackage.

**Comment by sid-kap** [comment]
Thanks!

**Comment by timbod7** [comment]
I couldn't really test the change without a fair bit of effort, as I don't think a diagrams library compatible with lens 4.14 has been released to hackage yet.

(But I think the new bounds are correct)

**Pull request closed without merging**
