### PR TITLE
Add G.R.Chart.Axis.Time module

### PR DESCRIPTION
**Pull request by phadej**
in short it adds `PlotValue UTCTime` and `PlotValue Day`

### CODE REVIEW

**Comment by phadej** [comment]
I'd like to simplify the `autoAxis` function, to use diffUTCTime

**Comment by timbod7** [comment]
This looks pretty good. Can you confirm that the existing tests based upon LocalTime still build and work?

**Comment by phadej** [comment]
I added travis script in #157, according to it; everything compiles fine.

**Comment by timbod7** [comment]
Thanks!

**Pull request merged**
