### PR TITLE
Travis

### LINKED ISSUE #156: Travis CI
I see there is no CI support, I can setup one; looks like that e.g. GHC 7.8.4 support bitrotted, CI would help with those issues.

Using `cabal new-build` it should be trivial (and quite maintenance free to do, i.e. no multiple `stack.yaml` to maintain).

### PR DESCRIPTION
**Pull request by phadej**
Based on #154, Resolves #156.

Example build: https://travis-ci.org/phadej/haskell-chart/builds/222307700

@timbod7, you only need to log into travis-ci.org and enable travis for this repository.

### CODE REVIEW

**Comment by phadej** [comment]
And I have to comment: thanks for making this package; it fills "I cannot do analytics in Haskell, bacause I cannot easily visualise results" hole very well for me.

**Comment by phadej** [comment]
I noticed there are `doctests` in `chart-tests`. I could move them to `Chart` and make them run.

Current approach with test-suite in different package from the library is quite problematic (to get to work with all `stack`, `cabal build` and `cabal new-build`)

**Comment by phadej** [comment]
And another comment: it seems that dependencies are quite unstable with GHC-7.4; I'd suggest (as Hackage Trustee) to lift lower-bound on `base >= 4.6` so it would be clear that only GHC >=7.6 is supported. FWIW Debian current stable, *jessie* provides GHC-7.6.

See https://ghc.haskell.org/trac/ghc/wiki/Commentary/Libraries/VersionHistory

**Comment by timbod7** [comment]
> Current approach with test-suite in different package from the library is quite problematic (to get to work with all stack, cabal build and cabal new-build)

The reason that the test suite is in a different package is that it exercises both the cairo and diagrams backend, and we don't want to make the core chart library depend on both of these (cairo is better, but hard to build on some platforms).

**Comment by timbod7** [comment]
I've not used travis before. After I sign in with my github credentials, I get sent straight back to the sign in page. Not sure what is going on.

**Comment by timbod7** [comment]
Also - I'll be off the air for the next week...

**Comment by phadej** [comment]
Unfortunately I have no idea how sign-up and sign-in process works with travis nowadays. IIRC it was quite straightforward, you should try again when you are back.

**Comment by phadej** [comment]
About tests: I was talking about moving **doctests** into `Chart`. The `chart-harness` indeed have to be as a separate package.

**Comment by timbod7** [comment]
According to the travis people, they fixed a bug which we preventing my login. Anyway it's working now. I pushed a minor commit and the automated build work perfectly, accross 4 ghc versions. Nice!

**Comment by timbod7** [comment]
Also - one question. If someone submits a PR, what do they have to do to show it builds cleanly via travis _before_ I merge it? Or will travis do that automatically?

**Pull request merged**
